window_height = 720
window_width = 1280
rotation_speed = 10
transition_speed = 10

exit = escape
toggle_rotation = r
toggle_texture = t
decrease_rotation_speed = y
increase_rotation_speed = u
move_object_up = up
move_object_down = down
move_object_left = left
move_object_right = right
move_object_forward = f
move_object_backward = b
